import type { Metadata } from "next";
import {
    Bebas_Neue,
    Cascadia_Code,
    Cascadia_Mono,
    Geist,
    Geist_Mono,
    JetBrains_Mono,
    Poppins,
    Rubik,
} from "next/font/google";
import localFont from "next/font/local";
import ClientLayout from "./client-layout";
import "./globals.css";

// Local Fonts
const helvetica = localFont({
    src: [
        {
            path: "./fonts/Helvetica.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/Helvetica-Bold.ttf",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/Helvetica-Compressed.otf",
            weight: "600",
            style: "normal",
        },
    ],
    variable: "--font-helvetica",
    display: "swap",
});

const helveticaNeue = localFont({
    src: [
        {
            path: "./fonts/HelveticaNeueMedium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeueBold.otf",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-helvetica-neue",
    display: "swap",
});

// Google Fonts
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    style: ["normal", "italic"],
    subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
    variable: "--font-bebas",
    weight: ["400"],
    style: ["normal"],
    subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
});

const rubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
});

const cascadia = Cascadia_Code({
    variable: "--font-cascadia",
    subsets: ["latin"],
});

const cascadiaMono = Cascadia_Mono({
    variable: "--font-cascadia-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`
                    ${geistSans.variable}
                    ${geistMono.variable}
                    ${jetBrainsMono.variable}
                    ${rubik.variable}
                    ${poppins.variable}
                    ${bebasNeue.variable}
                    ${cascadia.variable}
                    ${cascadiaMono.variable}
                    ${helvetica.variable}
                    ${helveticaNeue.variable}
                    bg-background text-foreground
                    transition-colors duration-500
                    font-helvetica-neue tracking-tighter font-bold
                `}
            >
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
