import type { Metadata } from "next";
import {
    Bebas_Neue,
    Cascadia_Code,
    Cascadia_Mono,
    Geist,
    Geist_Mono,
    JetBrains_Mono,
    Poppins,
    Rubik,
} from "next/font/google";
import ClientLayout from "./client-layout";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: [
        "100", // Thin
        "200", // Extra Light
        "300", // Light
        "400", // Regular
        "500", // Medium
        "600", // Semi Bold
        "700", // Bold
        "800", // Extra Bold
        "900", // Black
    ],
    style: ["normal", "italic"],
    subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
    variable: "--font-bebas",
    weight: [
        "400", // Regular
    ],
    style: ["normal"],
    subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
});

const rubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
});

const cascadia = Cascadia_Code({
    variable: "--font-cascadia",
    subsets: ["latin"],
});

const cascadiaMono = Cascadia_Mono({
    variable: "--font-cascadia-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${jetBrainsMono.variable} ${rubik.variable} ${poppins.variable} ${bebasNeue.variable} ${cascadia.variable} ${cascadiaMono.variable} bg-background text-foreground transition-colors duration-500 font-poppins tracking-tighter font-medium`}
            >
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
